"""Add SharedDataAccess model

Revision ID: 03855371b9c4
Revises: 53b8e5d276af
Create Date: 2025-05-06 14:57:22.206042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03855371b9c4'
down_revision = '53b8e5d276af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_data_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_data_access')
    # ### end Alembic commands ###
