"""Add title to SharedPlot

Revision ID: 08a4f29c900e
Revises: da07375948a6
Create Date: 2025-05-10 21:01:42.975768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a4f29c900e'
down_revision = 'da07375948a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_plot', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
