"""Add plot_html to SharedPlot

Revision ID: 9ed4082701a6
Revises: c6c08cb08891
Create Date: 2025-05-14 21:34:10.568436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed4082701a6'
down_revision = 'c6c08cb08891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plot_html', sa.Text(), nullable=True))
        batch_op.alter_column('plot_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_plot', schema=None) as batch_op:
        batch_op.alter_column('plot_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('plot_html')

    # ### end Alembic commands ###
