"""Add SharedDataAccess upgrade

Revision ID: cf60b9a2193b
Revises: 03855371b9c4
Create Date: 2025-05-06 16:39:21.722370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf60b9a2193b'
down_revision = '03855371b9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_point_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'data_point', ['data_point_id'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_point_id')

    # ### end Alembic commands ###
