"""Add created_at to DataPoint

Revision ID: da07375948a6
Revises: 301e29de3d19
Create Date: 2025-05-10 21:00:17.566348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da07375948a6'
down_revision = '301e29de3d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
